# Copyright Holder: TANIGUCHI Masaya
# Copyright Year: 2020
# License: MIT
# Project: Playbook Kallithea
- name: Install kallithea
  pip: 
    name: kallithea
    state: latest
    virtualenv: "{{ kallithea_root }}/.venv"
    virtualenv_command: python3 -m venv

- name: Create configuration
  command: >
    {{ kallithea_root }}/.venv/bin/kallithea-cli config-create {{ kallithea_root }}/kallithea.ini
  args:
    creates: "{{ kallithea_root }}/kallithea.ini"
    chdir: "{{ kallithea_root }}"

- name: Create directory for repositories
  file:
    path: "{{ kallithea_repos }}"
    state: directory

- name: Create database
  command: >
    {{ kallithea_root }}/.venv/bin/kallithea-cli db-create -c {{ kallithea_root}}/kallithea.ini
      --user={{ kallithea_user }}
      --password={{ kallithea_password }}
      --email={{ kallithea_email }}
      --repos={{ kallithea_repos }}
      --force-yes
  args:
    creates: "{{ kallithea_root }}/kallithea.db"
    chdir: "{{ kallithea_root }}"

- name: Build front-end
  shell: >
    . {{ kallithea_root }}/.venv/bin/activate &&
    {{ kallithea_root }}/.venv/bin/kallithea-cli front-end-build
  args:
    chdir: "{{ kallithea_root }}"

- name: Create systemd configuration
  template:
    src: kallithea.service.j2
    dest: /etc/systemd/system/kallithea.service
    mode: 664

- name: Enable kallithea
  systemd:
    name: kallithea
    enabled: yes
    state: started
