# Copyright Holder: TANIGUCHI Masaya
# Copyright Year: 2020
# License: MIT
# Project: Playbook Kallithea

- hosts: all
  vars_file: vars.yaml
  become: yes
  roles:
    - yum
    - kallithea
    - httpd
