# Copyright Holder: TANIGUCHI Masaya
# Copyright Year: 2020
# License: MIT
# Project: Playbook Kallithea

- hosts: all
  vars_files:
    - ./vars.yaml
  become: yes
  roles:
    - apt
    - kallithea
    - apache2
