# Copyright Holder: TANIGUCHI Masaya
# Copyright Year: 2020
# License: MIT
# Project: Playbook Kallithea

- hosts: localhost
  connection: local
  vars:
    kallithea_root: /srv/kallithea
    kallithea_user: admin
    kallithea_password: 3WzeJftriWK4B2Zk
    kallithea_email: admin@example.com
    kallithea_repos: /srv/repos
    kallithea_server_name: example.com
  become: yes
  roles:
    - apt
    - kallithea
    - apache2
