# Copyright Holder: TANIGUCHI Masaya
# Copyright Year: 2020
# License: MIT
# Project: Playbook Kallithea

- name: Install dependencies via apt
  apt: 
    name:
      - apache2
      - build-essential
      - git
      - libffi-dev
      - python3-dev
      - python3-venv
      - npm
    state: present
