# Copyright Holder: TANIGUCHI Masaya
# Copyright Year: 2020
# License: MIT
# Project: Playbook Kallithea
- name: Create apache configuration
  template:
    src: kallithea.conf.j2
    dest: /etc/httpd/conf.d/kallithea.conf
    mode: 664
- name: Restart apache
  systemd:
    name: httpd
    enabled: yes
    state: restarted
- name: Update SELinux
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
