- name: Download nodesource installer
  get_url: 
    url: https://rpm.nodesource.com/setup_12.x
    dest: /tmp/setup_12.x.bash
- name: Install nodesource
  command: bash /tmp/setup_12.x.bash
- name: Install dependencies via yum
  yum:
    name:
      - httpd
      - gcc
      - git
      - libffi-devel
      - python3-devel
      - nodejs
    state: present
