name: Ansible Playbook
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - centos
          - ubuntu
        include:
          - os: centos
            playbook: centos.yml
          - os: ubuntu
            playbook: debian.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker run ${{ matrix.os }}
        env:
          DOCKER_REGISTRY_URL: https://hub.docker.com/
        run: |
          sudo docker build . -f .github/workflows/${{ matrix.os }}.Dockerfile -t ${{ matrix.os }}
          sudo docker run -d -t --name=container ${{ matrix.os }}

      - name: ansible
        run: ansible-playbook -i 'container,' -c docker -u root ${{ matrix.playbook }}
